rz/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'rz.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
	url(r'^searcher/', include('searcher.urls', namespace='searcher')),
)

searcher/urls.py
from django.conf.urls import patterns, url
from searcher import views

urlpatterns = patterns('', 
	url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
	url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
	url(r'^(?P<campgroundquery_id>\d+)/execute/$', views.execute, name='execute'),
)

searcher/models.py
from django.db import models
from django.core.exceptions import ValidationError

class DayOfWeek(models.Model):
	name = models.CharField(max_length=10)
	date_code = models.SmallIntegerField()
	def __unicode__(self):
		return self.name

class Campground(models.Model):
	campground_name = models.CharField(max_length=100)
	park_id = models.SmallIntegerField()
	def __unicode__(self):
		return self.campground_name

class CampgroundQuery(models.Model):
	# loads choices from defined list
	eligible_days = models.ManyToManyField('DayOfWeek')
	campground = models.ForeignKey('Campground')
	stay_length = models.SmallIntegerField()
	start_date = models.DateField()
	end_date = models.DateField()
	last_query = models.DateTimeField(auto_now=True)
	active = models.BooleanField(default=True)

	def __unicode__(self):
		return (self.campground.campground_name + '-' + 
			self.end_date.strftime('%x'))


class Result(models.Model):
	data = models.TextField('response data')

searcher/forms.py
from django import forms
from django.contrib import admin
from searcher.models import CampgroundQuery

class CampgroundQueryAdminForm(forms.ModelForm):
	class Meta:
		model = CampgroundQuery
		widgets = {
			'eligible_days': forms.widgets.CheckboxSelectMultiple
		}

searcher/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.template import RequestContext, loader
import requests
import cgi
import datetime
import time
import xml.etree.ElementTree as ET
from datetime import date
from searcher.models import CampgroundQuery
#import pdb; pdb.set_trace()

class IndexView(generic.ListView):
	template_name = 'searcher/index.html'
	context_object_name = 'latest_campgroundquery_list'

	def get_queryset(self):
		"""Return the last five active campground_query objects."""
		return CampgroundQuery.objects.filter(active=True).order_by('-start_date')[:5]

class DetailView(generic.DetailView):
	model = CampgroundQuery
	template_name = 'searcher/detail.html'

class ResultsView(generic.DetailView):
	model = CampgroundQuery
	template_name = 'searcher/detail.html'


def execute(request, campgroundquery_id):
	c = get_object_or_404(CampgroundQuery, pk=campgroundquery_id)
	date_delta = datetime.timedelta(days=1)
	query_date = c.start_date
	eligible_days = c.eligible_days.values_list('date_code', flat=True)
	query_list = []
	while query_date <= c.end_date:
		#isoweekday: Monday=1, Sunday=7
		if query_date > date.today() and query_date.isoweekday() in eligible_days:
			# run the query for this day
			params = {
				'parkId': c.campground.park_id,
				'arvdate': query_date.strftime("%x"),
				'lengthOfStay': c.stay_length,
				'contractCode': 'CA',
				'siteType': 10001,
				'api_key': '3vtcjh2jfsnh78z7bjbfkdmj'}
			for i in range(3):
				# Active.com returns 403 (Forbidden) if we exceed rate limit
				# So attempt up to 3 tries
				req = requests.get("http://api.amp.active.com/camping/campsites/", params=params)
				if req.status_code == requests.codes.ok:
					break
				else:
					time.sleep(1)	# delay to avoid hitting rate limit 
			result = parse_xml(req.text)
			query_list.append({
				'query_url': req.url,
				'query_results': result['result_list'],
				'available_count': result['available_count'],
				'query_date': query_date,
			})		
		query_date += date_delta

	template = loader.get_template('searcher/results.html')
	context = RequestContext(request, {
		'query_desc': "{0} from {1} to {2}".format(c.campground, c.start_date, c.end_date),
		'query_set': query_list,
	})
	return HttpResponse(template.render(context))

def parse_xml(xml_response):
	resultset = ET.fromstring(xml_response)
	result_list = []
	count = 0
	for result in resultset.findall('result'):
		result_list.append({
			'site': result.get('Site'),
			'site_id': result.get('SiteId'),
			'availability_status': result.get('availabilityStatus')})
		if result.get('availabilityStatus') == 'Y':
			count+=1
	return {'available_count': count, 'result_list':result_list}

searcher/templates/searcher/detail.html
<h1>{{ campgroundquery }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<p>Searching <i>{{ campgroundquery.campground }}</i> 
from <i>{{campgroundquery.start_date}}</i> to <i>{{campgroundquery.end_date}}</i>
for <i>{{ campgroundquery.eligible_days.all|join:"/" }}</i> availability
for <i>{{ campgroundquery.stay_length }}</i> nights.
<form action="{% url 'searcher:execute' campgroundquery.id %}" method="get">
{% csrf_token %}
<input type="submit" value="Execute" />
</form>

searcher/templates/searcher/index.html
Hello
{% if latest_campgroundquery_list %}
	<ul>
	{% for query in latest_campgroundquery_list %}
		<li><a href="{% url 'searcher:detail' query.id %}">{{ query.campground }}</a></li>
	{% endfor %}
	</ul>
{% else %}
	<p>None available</p>
{% endif %}
Goodbye

searcher/templates/searcher/results.html
<style>
table {
	border-collapse: collapse;
}
table, th, td {
	border: 1px solid black
}
th, td {
	padding: .3em;
}
.available {
	background-color: #cfc;
}
.unavail {
	display: none;
}
</style>

<h1>{{ query_desc }}</h1>

{% for query in query_set %}
	<h2><a href="{{ query.query_url }}">{{ query.query_date|date:"N j, Y (D)" }}</a></h2>
	{% if query.available_count > 0 %}
	<table>
	<tr><td>site</td><td>site_id</td><td>status</td></tr>
	{% for result in query.query_results %}
	<tr class="{% if result.availability_status == 'Y' %}available{% else %}unavail{% endif %}">
		<td>{{ result.site }}</td>
		<td>{{ result.site_id }}</td>
		<td>{{ result.availability_status }}</td>
	</tr>
	{% endfor %}
	</table>
	{% else %}
	<p>No availability</p>
	{% endif %}
{% endfor %}